name: quoteoftheday
description: Premium Quote of the Day app.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  shared_preferences: ^2.5.3
  share_plus: ^10.1.4
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/quotes.json
